name: create release binary
on:
  release:
    types: [created]
jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - s390x
          - arm
          - arm64
          - ppc64le
    steps:
      - uses: actions/checkout@v3
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: linux
          goversion: 1.19
          ldflags: >
            -extldflags -static
            -X "main.Version=${{ github.ref }}"
            -w
            -s
          md5sum: "FALSE"
          sha256sum: "TRUE"
          extra_files: LICENSE README.md
        env:
          CGO_ENABLED: "0"
